import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const prisma = new PrismaClient()

const WP = "https://khaki-chough-664761.hostingersite.com/wp-content/uploads"

async function main() {
  // Create admin user
  const hashedPassword = await bcrypt.hash("A29admin!2026", 12)

  await prisma.admin.upsert({
    where: { email: "admin@a29imoveis.com" },
    update: {},
    create: {
      email: "admin@a29imoveis.com",
      password: hashedPassword,
      name: "Anelize",
    },
  })

  console.log("Admin created: admin@a29imoveis.com")

  // Seed imóveis
  const imoveis = [
    {
      slug: "meo-neoville",
      nome: "Meo Neoville",
      tipo: "Apartamento",
      status: "Lançamento",
      bairro: "Neoville",
      cidade: "Curitiba",
      endereco: "Rua José Marcelino da Silva Júnior, 941 - Neoville, Curitiba - PR, 81312-080",
      preco: "R$ 574.417",
      precoApartir: true,
      area: "2 e 3 quartos",
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 2,
      descricao:
        "O Meo Neoville é o novo empreendimento da Rottas na região do Neoville em Curitiba. Com opções de 2 e 3 quartos, incluindo apartamentos garden com área externa privativa, o projeto combina design contemporâneo com infraestrutura completa de lazer. Entrega prevista para março de 2026.",
      destaque: true,
      imagens: [
        `${WP}/2026/01/072NEO-IMA-000-ESTAR-JANTAR-3Q-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-ESTAR-JANTAR-2Q-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-SUITE-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-QUARTO-01-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-GARDEN-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-ACADEMIA-FINAL-scaled.png`,
        `${WP}/2026/01/072NEO-IMA-000-SALAO-DE-FESTAS-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-ESPACO-KIDS-FINAL-scaled.jpg`,
        `${WP}/2026/01/072NEO-IMA-000-DELIVERY-FINAL-scaled.jpg`,
      ],
      construtora: "Rottas",
      entrega: "Março de 2026",
      diferenciais: [
        "Cozinha integrada à sala",
        "Churrasqueira a carvão em todas as sacadas",
        "Bancadas em granito com cuba de embutir",
        "Infraestrutura para ar-condicionado",
        "Piso cerâmico/porcelanato nas áreas molhadas",
        "Esquadrias de alumínio preto",
        "Medição individual de água e gás",
        "Aquecimento a gás para chuveiros e cozinha",
      ],
      lazer: [
        "Rooftop Garden",
        "Academia",
        "Market / Delivery",
        "Bike Share",
        "Jogos ao ar livre",
        "Salão de festas",
        "Brinquedoteca",
        "Piscina adulto e infantil",
        "Playground",
        "Quiosque churrasqueira",
        "Car Wash",
        "Quadra poliesportiva",
        "Pet Square",
      ],
      ordem: 0,
    },
    {
      slug: "vega-neoville",
      nome: "Vega Neoville",
      tipo: "Apartamento",
      status: "Lançamento",
      bairro: "Cidade Industrial",
      cidade: "Curitiba",
      endereco: "Rua Agostinho Brusamolin, 141 - Cidade Industrial de Curitiba, Curitiba - PR, 81312-090",
      preco: "R$ 389.230",
      precoApartir: true,
      area: "2 e 3 quartos",
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 1,
      descricao:
        "O Vega Neoville é o novo lançamento da Rottas na região da Cidade Industrial de Curitiba. Com apartamentos tipo e garden de 2 e 3 quartos, oferece arquitetura contemporânea, paisagismo funcional e uma completa infraestrutura de lazer. Entrega prevista para agosto de 2028.",
      destaque: true,
      imagens: [
        `${WP}/2026/01/VEGA-Neoville-Torre-NOTURNA-r01-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Torre-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Aerea-Geral-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/1026NEO-IMG-003-AREALAZER-R00-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Piscina-r01-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/1026NEO-IMG-005-PORTARIANOTURNA-R00-scaled.jpg`,
        `${WP}/2026/01/1026NEO-IMG-006-SACADA-R00-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Family-Garden-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Playground-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Quadra-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/1026NEO-IMG-PET-R00-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Garden-r01-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Gourmet-FINAL-Rupt-3D-scaled.jpg`,
        `${WP}/2026/01/VEGA-Neoville-Quiosque-FINAL-Rupt-3D-scaled.jpg`,
      ],
      construtora: "Rottas",
      entrega: "Agosto de 2028",
      diferenciais: [
        "Cozinha integrada à sala",
        "Churrasqueira a carvão em todas as unidades",
        "Infraestrutura para ar-condicionado",
        "Piso cerâmico 68x68cm retificado",
        "Esquadrias de alumínio",
        "Arquitetura contemporânea",
        "Medição individual de água e gás",
        "Vagas de visitantes",
        "Paisagismo funcional",
      ],
      lazer: [
        "Portaria personalizada",
        "Piscina adulto e infantil",
        "Salão de festas gourmet",
        "Praça de chegada",
        "Playground",
        "Quiosque com churrasqueira",
        "Jogos ao ar livre",
        "Pomar",
        "Quadra de vôlei de areia",
        "Pet Square",
        "Family Garden",
        "Bicicletário",
      ],
      ordem: 1,
    },
    {
      slug: "door-7710",
      nome: "Door 7710",
      tipo: "Apartamento",
      status: "Pronto",
      bairro: "Portão",
      cidade: "Curitiba",
      endereco: "Av. da República, 7710 - Portão, Curitiba - PR, 80610-220",
      preco: "R$ 815.507",
      precoApartir: true,
      area: "2 e 3 quartos",
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 2,
      descricao:
        "O Door 7710 é um empreendimento pronto para morar no bairro Portão, uma das regiões mais valorizadas de Curitiba. Com apenas 2 unidades disponíveis, oferece acabamentos premium, paredes reversíveis para ampliação dos ambientes e infraestrutura completa. Entregue em agosto de 2025.",
      destaque: true,
      imagens: [
        `${WP}/2026/01/ambiente_06.jpg`,
        `${WP}/2026/01/ambiente_04.jpg`,
        `${WP}/2026/01/ambiente_05.jpg`,
        `${WP}/2026/01/ambiente_01.jpg`,
        `${WP}/2026/01/diferencial_piscina.jpg`,
        `${WP}/2026/01/diferencial_academia.jpg`,
        `${WP}/2026/01/diferencial_academia_02.jpg`,
        `${WP}/2026/01/diferencial_coworking.jpg`,
        `${WP}/2026/01/diferencial_delivery.jpg`,
        `${WP}/2026/01/diferencial_brinquedoteca.jpg`,
        `${WP}/2026/01/diferencial_petsquare.jpg`,
        `${WP}/2026/01/diferencial_petcare.jpg`,
        `${WP}/2026/01/diferencial_bicicletario.jpg`,
        `${WP}/2026/01/img_localizacao-1.jpg`,
      ],
      construtora: "Door Engenharia",
      entrega: "Agosto de 2025 (Pronto)",
      diferenciais: [
        "Paredes reversíveis para ampliação",
        "Forro de gesso em todos os ambientes",
        "Cozinha integrada à sala",
        "Ponto de hidromassagem no terraço",
        "Vedação acústica nas portas",
        "Persianas integradas nos dormitórios",
        "Porcelanato retificado 60x60cm",
        "Bancadas em granito nos banheiros",
        "Churrasqueira a carvão com nicho",
        "Aquecimento a gás",
        "Infraestrutura completa para ar-condicionado",
        "Porta de entrada com largura acessível",
      ],
      lazer: [
        "Academia",
        "Coworking",
        "Lavanderia",
        "Pet Square",
        "Pet Care",
        "Piscina Sky",
        "Churrasqueira Rooftop",
        "Bicicletário",
        "Delivery / Market",
        "Área kids ao ar livre",
        "Salão de festas",
        "Brinquedoteca",
        "Playground",
        "Lobby",
      ],
      ordem: 2,
    },
    {
      slug: "equi",
      nome: "Équi Seminário",
      tipo: "Apartamento",
      status: "Lançamento",
      bairro: "Seminário",
      cidade: "Curitiba",
      endereco: "R. Dep. Nilson Ribas, 776 - Seminário, Curitiba - PR, 80740-510",
      preco: "R$ 873.301",
      precoApartir: true,
      area: "2 e 3 quartos + Duplex Penthouse",
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 2,
      descricao:
        "O Équi Seminário é um lançamento da Rottas no bairro Seminário, uma das regiões mais nobres de Curitiba. Oferece apartamentos de 2 e 3 quartos além de duplex penthouses com 3 suítes ou 4 quartos. Conta com bosque privativo de 950m² e infraestrutura para veículos elétricos. Entrega prevista para agosto de 2026.",
      destaque: true,
      imagens: [
        `${WP}/2026/01/equi_n_fachadaalta.jpg`,
        `${WP}/2026/01/terraco.jpg`,
        `${WP}/2026/01/suite_duplex.jpg`,
        `${WP}/2026/01/sala_duplex.jpg`,
        `${WP}/2026/01/salao_de_festas.jpg`,
        `${WP}/2026/01/salao_de_festas2.jpg`,
        `${WP}/2026/01/praca.jpg`,
        `${WP}/2026/01/market_place.jpg`,
        `${WP}/2026/01/hall.jpg`,
        `${WP}/2026/01/delivery.jpg`,
        `${WP}/2026/01/deck_festas.jpg`,
        `${WP}/2026/01/brinquedoteca.jpg`,
        `${WP}/2026/01/academia.jpg`,
        `${WP}/2026/01/pub.jpg`,
        `${WP}/2026/01/piscina.jpg`,
      ],
      construtora: "Rottas",
      entrega: "Agosto de 2026",
      diferenciais: [
        "Parede reversível para ampliação da sala",
        "Forro de gesso em todos os ambientes",
        "Cozinha integrada",
        "Aquecimento a gás",
        "Esquadrias de alumínio com persianas integradas",
        "Porcelanato retificado 60x60cm",
        "Bancadas em granito",
        "Churrasqueira a carvão em todas as sacadas",
        "Infraestrutura para veículos elétricos/híbridos",
        "Infraestrutura para ar-condicionado",
      ],
      lazer: [
        "Hall de entrada",
        "Salão de festas",
        "Pub Gourmet",
        "Brinquedoteca",
        "Academia",
        "Quiosque churrasqueira",
        "Market Place",
        "Praça central",
        "Piscina",
        "Bosque privativo (950m²)",
        "Estacionamento térreo",
        "Deck festas",
      ],
      ordem: 3,
    },
    {
      slug: "paseo-de-avila",
      nome: "Paseo de Ávila",
      tipo: "Condomínio",
      status: "Lançamento",
      bairro: "Neoville",
      cidade: "Curitiba",
      endereco: "R. Valentin Deda, 150 - Cidade Industrial de Curitiba, Curitiba - PR, 81130-140",
      preco: "R$ 574.417",
      precoApartir: true,
      area: "Lotes de 180m² a 284m²",
      descricao:
        "Condomínio fechado horizontal com 61 lotes na região do Neoville, a 20 minutos do centro de Curitiba. Inspirado na cidade de Ávila, na Espanha, o empreendimento cultiva jardins e espaços de convivência para seus moradores, com infraestrutura completa de lazer e segurança. Entrega prevista para 2027.",
      destaque: false,
      imagens: [
        `${WP}/2026/01/implantacao-neoville_03-1.webp`,
        `${WP}/2026/01/14-1.webp`,
        `${WP}/2026/01/13-1.webp`,
        `${WP}/2026/01/11-1.webp`,
        `${WP}/2026/01/1-1.webp`,
        `${WP}/2026/01/10-1.webp`,
        `${WP}/2026/01/9-1.webp`,
        `${WP}/2026/01/8-1.webp`,
        `${WP}/2026/01/7-1.webp`,
        `${WP}/2026/01/19-1.webp`,
        `${WP}/2026/01/3-1.webp`,
        `${WP}/2026/01/4-1-1.webp`,
        `${WP}/2026/01/2-1.webp`,
        `${WP}/2026/01/5.webp`,
        `${WP}/2026/01/design-sem-nome-4.webp`,
      ],
      construtora: "Canet Júnior S.A.",
      entrega: "2027",
      diferenciais: [
        "Condomínio fechado horizontal",
        "61 lotes de 180m² a 284m²",
        "Portaria com porte-cochère e delivery",
        "Infraestrutura subterrânea",
        "Iluminação LED nas vias",
      ],
      lazer: [
        "Salão de festas (150 pessoas)",
        "Lounge externo",
        "Playground",
        "Mini-golf",
        "Academia",
        "Quadra esportiva com arquibancada",
        "Quiosque churrasqueira",
        "Pet Park",
        "Pet Place",
        "Praças temáticas",
        "Vagas de visitantes",
      ],
      ordem: 4,
    },
    {
      slug: "paseo-santiago",
      nome: "Paseo Santiago",
      tipo: "Condomínio",
      status: "Lançamento",
      bairro: "Neoville",
      cidade: "Curitiba",
      endereco: "Rua José Marcelino da Silva Júnior, 619 - Neoville, Curitiba - PR, 81020-490",
      preco: "R$ 609.003",
      precoApartir: true,
      area: "Lotes de 171m² a 288m²",
      descricao:
        "Condomínio fechado horizontal com 54 lotes na região do Neoville. Inspirado no Caminho de Santiago de Compostela, o empreendimento traz conceito de renovação e bem-estar. Conta com jardins temáticos, praça com fonte ornamental e infraestrutura completa subterrânea. Financiamento direto com a incorporadora. Entrega prevista para agosto de 2026.",
      destaque: false,
      imagens: [
        `${WP}/2026/01/Vista-aerea.png`,
        `${WP}/2026/01/Portaria-1-1.png`,
        `${WP}/2026/01/Portaria-2-1.png`,
        `${WP}/2026/01/Salao-de-Festas.png`,
        `${WP}/2026/01/Salao-de-festas-panoramica.png`,
        `${WP}/2026/01/Lounge-do-salao-de-festas.png`,
        `${WP}/2026/01/Praca-da-Fonte.png`,
        `${WP}/2026/01/Playground-Academia.png`,
        `${WP}/2026/01/Academia.png`,
        `${WP}/2026/01/Quadra-esportiva.png`,
        `${WP}/2026/01/Espaco-churrasqueira.png`,
        `${WP}/2026/01/Pet-Place.png`,
        `${WP}/2026/01/Jardim-dos-sabores.png`,
        `${WP}/2026/01/Jardim-Quatro-Estacoes.png`,
        `${WP}/2026/01/Jardim-das-sensacoes.png`,
        `${WP}/2026/01/Via-interna.png`,
        `${WP}/2026/01/Implantacao-legal.png`,
      ],
      construtora: "Canet Júnior S.A.",
      entrega: "Agosto de 2026",
      diferenciais: [
        "Condomínio fechado horizontal",
        "54 lotes de 171m² a 288m²",
        "Financiamento direto com a incorporadora",
        "Infraestrutura subterrânea completa",
        "Iluminação LED nas vias",
        "Rede de água, esgoto e gás",
      ],
      lazer: [
        "Portaria com monitoramento",
        "Salão de festas com lounge externo",
        "Praça da Fonte (fonte ornamental)",
        "Dois playgrounds",
        "Quadra esportiva com arquibancada",
        "Quiosque churrasqueira",
        "Academia com área de alongamento externa",
        "Deck de relaxamento",
        "Área pet com bebedouro",
        "Jardim dos Sabores",
        "Jardim Quatro Estações",
        "Jardim das Sensações",
      ],
      ordem: 5,
    },
    {
      slug: "casa-condominio-veredas",
      nome: "Casa Condomínio Veredas",
      tipo: "Casa",
      status: "Pronto",
      bairro: "São Marcos",
      cidade: "Campo Largo",
      endereco: "R. Casemiro de Abreu, 30 - Casa 113 - São Marcos, Campo Largo - PR, 83602-665",
      preco: "R$ 550.000",
      area: "3 quartos (1 suíte)",
      quartos: 3,
      suites: 1,
      banheiros: 3,
      vagas: 3,
      descricao:
        "Casa pronta em condomínio fechado no bairro São Marcos, a 6 minutos do centro de Campo Largo. Com 3 quartos sendo 1 suíte master com closet, pé-direito duplo na sala, área gourmet, varanda e quintal privativo. Escritura registrada, pronta para morar. Acabamentos de alto padrão com porcelanato nas áreas sociais e laminado nos dormitórios.",
      destaque: false,
      imagens: [
        `${WP}/2026/01/2025-04-29-casa161-12-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-11-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-10-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-9-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-8-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-7-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-4-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-2-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-1-1-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-37-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-73-scaled.jpg`,
        `${WP}/2026/01/2025-04-29-casa161-76-scaled.jpg`,
      ],
      entrega: "Pronto (Escritura registrada)",
      diferenciais: [
        "Suíte master com closet",
        "Fechadura eletrônica na porta de entrada",
        "Piso laminado nos dormitórios",
        "Porcelanato de alto padrão nas áreas sociais",
        "Pé-direito duplo na sala",
        "Área gourmet",
        "Infraestrutura para ar-condicionado",
        "Infraestrutura para aquecimento",
        "Varanda e quintal privativo",
      ],
      lazer: [
        "Portaria 24h com controle remoto",
        "Ruas asfaltadas com iluminação LED",
        "Sistema de tratamento de água",
        "Rede de esgoto interna",
        "Salão de festas",
        "Playground",
        "Churrasqueira",
        "Área verde (~6.850m²)",
      ],
      ordem: 6,
    },
    {
      slug: "sobrado-pinheirinho",
      nome: "Sobrado Frente para Rua",
      tipo: "Sobrado",
      status: "Pronto",
      bairro: "Pinheirinho",
      cidade: "Curitiba",
      endereco: "Rua Doutor João Estevam dos Santos - Pinheirinho, Curitiba - PR, 81825-132",
      preco: "R$ 499.000",
      area: "130m² construídos",
      quartos: 2,
      suites: 2,
      banheiros: 3,
      vagas: 4,
      descricao:
        "Sobrado frente para rua no Pinheirinho, pronto para morar. Com 130m² construídos, 2 suítes com sacada, 3 banheiros e garagem coberta para 4 veículos. Conta com armários planejados em todos os cômodos, cozinha americana, churrasqueira e dependência de empregada. Orientação solar nascente/poente. Aceita pets.",
      destaque: false,
      imagens: [
        `${WP}/2026/01/IMG_4192_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4195_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4198_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4199_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4210_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4214_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4215_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4217_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4223_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4224_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4225_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4227_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4230_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4232_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4233_1-scaled.jpg`,
        `${WP}/2026/01/IMG_4234_1-scaled.jpg`,
      ],
      entrega: "Pronto para morar",
      diferenciais: [
        "Armários planejados em todos os cômodos",
        "Cozinha americana",
        "Churrasqueira",
        "2 suítes com sacada",
        "Ar-condicionado na suíte frontal",
        "Lavabo",
        "Dependência de empregada",
        "Garagem coberta para 4 veículos",
        "Aceita pets",
        "Orientação nascente/poente",
      ],
      ordem: 7,
    },
  ]

  for (const imovel of imoveis) {
    await prisma.imovel.upsert({
      where: { slug: imovel.slug },
      update: imovel,
      create: imovel,
    })
    console.log(`Imóvel criado: ${imovel.nome}`)
  }

  console.log("\nSeed concluído!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
